### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by iProgYou** [alexzhou415/Kelp#1]
# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`
## Comments
- You likely need a foreign key in your businesses table to reference the user that created the business
- `hours` may be hard to put into a string. If you want to do it, you will need to write a custom validation. This data is not necessary to start the businesses portion so you could add it later on.
- tags will need to be a separate table likely. It is likely not absolutely necessary for the beginning of the app

**Comment by alexzhou415** [comment]
Made :businesses hours able to be a null field.
Added a creator foreign key referencing :users and removed tags column from :businesses.
Added tags and business tags tables.
