### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by iProgYou** [alexzhou415/Kelp#2]
# MVP List
- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points
## Comments
- Name is great
- Likely your MVP's are a bit too ambitious currently. You may need to scale back to build out the features and then expand on them later. For example, your 3 MVP has a ton of different features, but I would say the the main part of Yelp is the interaction between business pages and users reviewing a business. Let me know if you need additional explanation.

**Comment by alexzhou415** [comment]
Users can also delete their reviews.

**Comment by iProgYou** [comment]
If you are ever unsure of how you should proceed through an MVP let me know.
